version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    build: /home/ubuntu/docker-poc/backend
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: my_database
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      SERVER_PORT: 8081
    depends_on:
      - mysql
    ports:
      - "8081:8081"

  frontend:
    build: /home/ubuntu/docker-poc/frontend
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
